name: passenger_tyvaa
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dots_indicator: ^4.0.1
  dio: any
  flutter_secure_storage: any
  mask_text_input_formatter: ^2.9.0
  smooth_page_indicator: any
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  convex_bottom_bar: any
  stylish_bottom_bar: ^1.1.1
  flutter_spinkit: any
  lottie: any
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  flutter_intl: ^0.0.1
  intl: ^0.20.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0
  modal_bottom_sheet: ^3.0.0
  change_app_package_name: ^1.5.0
  firebase_core: any
  firebase_messaging: any
  auto_size_text: ^3.0.0
  hive: any
  animated_text_kit: ^4.2.3
  socket_io_client: ^3.1.2
  connectivity_plus: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/chatbot_pic/
    - assets/icons/
    - assets/flags/
    - assets/images/
